# Generated by Django 5.0.7 on 2024-07-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=255)),
                ('Stock', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
            ],
        ),
    ]
