# Generated by Django 5.0.7 on 2024-07-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, max_length=2000, null=True, upload_to=''),
        ),
    ]
